@startuml
class CompraItem {
    + CompraItem()
    + CompraItem(cantidad:int, libroId:int, libro:Libro, compraId:int, compra:Compra)
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
    + Cantidad : int <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + CompraId : int <<get>> <<set>>
}
CompraItem --> "Libro" Libro
CompraItem --> "Compra" Compra
@enduml
