@startuml
hide methods
!include .\Compra.puml
!include .\CompraItem.puml
!include .\Libro.puml
!include .\ApplicationUser.puml
!include .\MetodoPago.puml
!include .\Visa.puml
!include .\GooglePay.puml
!include .\PayPal.puml
!include .\Editorial.puml
!include .\Genero.puml
@enduml