@startuml
class Editorial {
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + <<virtual>> Libros : IList<Libro> <<get>> <<set>>
    + Editorial()
    + Editorial(id:int, nombre:string)
}
@enduml
