@startuml
class Editorial {
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Editorial()
    + Editorial(id:int, nombre:string)
}
class "IList`1"<T> {
}
Editorial --> "Libros<Libro>" "IList`1"
@enduml
