@startuml
class PayPal {
    + NumeroTelefono : string <<get>> <<set>>
    + PayPal()
    + PayPal(numeroTelefono:string)
    + <<override>> Equals(obj:object) : bool
}
MetodoPago <|-- PayPal
@enduml
