@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(id:int, fechaReposicion:DateTime, precioTotal:double, comentario:string)
    + Id : int <<get>> <<set>>
    + PrecioTotal : double <<get>> <<set>>
    + Comentario : string <<get>> <<set>>
}
Reposicion --> "FechaReposicion" DateTime
@enduml
