@startuml
class ReponeItem {
    + ReponeItem()
    + ReponeItem(id:int, cantidad:int, fechaReposicion:DateTime)
    + Id : int <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + FechaReposicion : DateTime <<get>> <<set>>
}
@enduml
