@startuml
class Resena {
    + Id : int <<get>> <<set>>
    + Fecha : DateTime <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + <<virtual>> ApplicationUser : ApplicationUser? <<get>> <<set>>
    + <<virtual>> ResenaItems : IList<ResenaItem> <<get>> <<set>>
    + Resena()
    + Resena(id:int, fecha:DateTime, applicationUserId:string)
}
@enduml
